### ISSUE TITLE
Thanks for this manual

### ISSUE THREAD

**Issue by parlen-colen** [fragon10/NOS_C-650W#1]
Thank you so much for this. I lost mine (plus it was in Norwegian or Danish, cannot recall).

I would like to connect the keyboard via usevia.äpp, but itt says no HID compatible device. Do you know if that's possible? sorry for asking this, but it's just that has been very difficult to find any information about the keyboard

**Comment by igniztion** [comment]
The C-650W does not support VIA or QMK.
