### ISSUE TITLE
TAB and Ctrl switched place

### ISSUE THREAD

**Issue by Fnordbert** [fragon10/NOS_C-650W#2]
Hi, and thanks for creating this manual :-)

We seem to have stumbled into a mode where the left Ctrl and TAB have changed place. 
Any idea what it might be before we do a reset?

**Comment by fragon10** [comment]
This is a very late response, and no, I don't know why these two keys would have swapped functionality, but I suspect that the incorrect operating system has been selected [Windows / Mac -Mode](https://github.com/fragon10/NOS_C-650W/blob/main/NOS_C-650W_en_manual.md#windows--mac--mode)
